root: true
env:
  browser: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:jest-dom/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:testing-library/react
ignorePatterns:
  - dist
  - .eslintrc.cjs
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
    - ./tsconfig.node.json
plugins:
  - react-refresh
settings:
  react:
    version: detect
rules:
  react-refresh/only-export-components:
    - warn
    - { allowConstantExport: true }
